version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  adserver:
    build: ./adserver
    ports:
      - "8081"
    command: adserver
    restart: always
    links:
      - kafka
    environment:
      - "constraint:layer==Nodes"
      - LOG_LEVEL=debug
      - MESSAGE_BROKERS=kafka:9092
      - CAMPAIGNS_FILE=/campaigns.json
    volumes:
      - ./campaigns.json:/campaigns.json
  adserverlogs:
    build: ./adserverlog
    ports:
      - "8082"
    command: adserverlogs
    restart: always
    links:
      - kafka
    environment:
      - "constraint:layer==Nodes"
      - LOG_LEVEL=debug
      - MESSAGE_BROKERS=kafka:9092